name: Check IPNS

on:
  push:
    branches:
      - mpetrun5/reocurring-action

permissions: read-all

jobs:
  check_ipns:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        key: [DEV, TEST]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Load IPNS key
        shell: bash
        run: |
          echo "${{secrets[format('KEY_{0}', matrix.key)]}}" >> ipnskey.pem
      - uses: sygmaprotocol/setup-ipfs@master
        with:
          run_daemon: true
      - name: Import IPNS key
        shell: bash
        run: |
          echo "IPNS=$(ipfs key import IPNSKey -f pem-pkcs8-cleartext ipnskey.pem | grep -o -E "\w{62}")" >> $GITHUB_ENV

      - name: Lowercase key
        run: KEY=

      - name: Check IPNS
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 60
          max_attempts: 10
          command: diff <(curl -X GET https://cloudflare-ipfs.com/ipns/${{ env.IPNS }}) <(cat "config.${${{matrix.key}},,}.json")
