name: Publish devnet configuration

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  # Publish devnet configuration to IPFS
  publish_ipfs:
    runs-on: ubuntu-latest
    # set CID as output
    outputs:
      cid: ${{ steps.ipfspub.outputs.cid }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to IPFS
        uses: aquiladev/ipfs-action@master
        id: ipfspub
        with:
          path: ./config.dev.json
          service: infura
          infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }}
          infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }}

  # Upload configuration file to CS Storage
  publish_storage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag uploader
      - name: Upload new configuration
        run: docker run -e ENV='dev' -e CS_STORAGE_BUCKET_ID=${{ secrets.CS_STORAGE_BUCKET_ID }} -e CS_STORAGE_API_KEY=${{ secrets.CS_STORAGE_API_KEY }} --name dev-uploader uploader ./config-uploader
      - name: Print logs
        if: always()
        run: |
          docker ps -a
          docker logs dev-uploader
