name: Update docs addresses reminder

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  detect-update-addresses-checkbox:
    runs-on: ubuntu-latest
    outputs:
      checked: ${{ steps.detect.outputs.checked }}
    steps:
      - uses: marocchino/checkbox-action@v1
        id: detect
        with:
          action: 'detect'

  validate-update-addresses-checkbox:
    runs-on: ubuntu-latest
    needs: detect
    if: ${{ contains(fromJSON(needs.detect.outputs.checked)) }}
    uses: actions/github-script@v3
    with:
      script: |
          core.setFailed('Update adderesses checkbox not checked!')
