name: Validate configuration JSON files

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate-json:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - name: validate-devnet-json
            schema: /schema.json
            json: /testnet/shared-config-dev.json
          - name: validate-testnet-json
            schema: /schema.json
            json: /testnet/shared-config-test.json
          - name: validate-mainnet-json
            schema: /schema.json
            json: /mainnet/shared-config-mainnet.json
          - name: validate-x-json
            schema: /schema.json
            json: /testnet/shared-config-x.json
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ${{ matrix.config.schema }}
          jsons: ${{ matrix.config.json }}
