name: Validate configuration JSON files

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate-devnet-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: /schema.json
          jsons: /testnet/shared-config-dev.json

  validate-testnet-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: /schema.json
          jsons: /testnet/shared-config-test.json

  validate-mainnet-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: /schema.json
          jsons: /mainnet/shared-config-mainnet.json
  validate-x-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: /schema.json
          jsons: /testnet/shared-config-x.json